spring:
  mail:
    # 发送邮件的服务器主机地址
    host: smtp.qq.com
    # 邮箱的地址
    username: 2998701715@qq.com
    # 第三份服务授权码
    password: wtswhljukcutddac
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        debug: ture
